project_name = "10weeksofcloudops-tf"
region = "us-west-2"
VPC_CIDR                = "10.0.0.0/16"
PUB_SUB_1_A_CIDR        = "10.0.0.0/24"
PUB_SUB_2_B_CIDR        = "10.0.1.0/24"
PRI_SUB_3_A_CIDR        = "10.0.2.0/24"
PRI_SUB_4_B_CIDR        = "10.0.3.0/24"
PRI_SUB_5_A_CIDR        = "10.0.4.0/24"
PRI_SUB_6_B_CIDR        = "10.0.5.0/24"
#DB_USERNAME             = "admin"
#DB_PASSWORD             = "Piyush-123"
#CERTIFICATE_DOMAIN_NAME = ""
#ADDITIONAL_DOMAIN_NAME  = ""
my_ip                        = "49.37.208.141/32" 
#include your ip so you can ssh from yours only.
image_name                   = "ubuntu/images/hvm-ssd/ubuntu"
instance_type                = "t2.micro"
desired_capacity             = "1"
min_size                     = "1"
max_size                     = "3"
domain_name                  = "lakshminarasimmanbiz.study"
alternative_name             = "*.lakshminarasimmanbiz.study"

